# Numpy

### Import Statement

In [3]:
import numpy as np

### Creating a numpy matrix

In [4]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

### Flattening the matrix

In [5]:
a.flatten()

array([1, 2, 3, 4, 5, 6])

### Reshape a matrix

In [7]:
a.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

### Matrix Operations

In [31]:
# Matrix Addition
b = np.array([[7, 8, 9], [10, 11, 12]])
print(a + b)

# Matrix Subtraction
print()
print(a - b)

# Matrix Multiplication
c = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print()
print(c * d)

[[ 8 10 12]
 [14 16 18]]

[[-6 -6 -6]
 [-6 -6 -6]]

[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


### Getting the Sum of the Matrix

In [33]:
print(a.sum())

21


### Sorting a Matrix

In [36]:
np.sort(np.array([[4,2,1], [10, 8, 3]]))

array([[ 1,  2,  4],
       [ 3,  8, 10]])